version: '3'
services:
  opensora:
    build:
      context: .
      dockerfile: Dockerfile
    image: opensora
    ports:
      - 7860:7860
    volumes:
      - ./:/data
      - .cache:/root/.cache
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    tty: true
    stdin_open: true